name: niyamdrishti_inspector
description: Inspector UI for NiyamDrishti AI (Member 4 - Frontend)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7   # lets us open camera/gallery to pick an image
  http: ^1.2.0           # HTTP REST client for backend communication

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
